# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-16 08:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='liked_by',
            field=models.ManyToManyField(null=True, related_name='like_songs', through='music.LikeShip', to=settings.AUTH_USER_MODEL),
        ),
    ]
