# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-16 08:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20170116_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='liked_by',
            field=models.ManyToManyField(related_name='like_songs', through='music.LikeShip', to=settings.AUTH_USER_MODEL),
        ),
    ]
