# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-16 08:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20170116_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='liked_by',
        ),
    ]
