# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-16 08:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0004_remove_song_liked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='like_songs', through='music.LikeShip', to=settings.AUTH_USER_MODEL),
        ),
    ]
