# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-16 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_auto_20170116_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='total_likes',
            field=models.IntegerField(default=0),
        ),
    ]
