# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-20 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0011_auto_20170120_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
