# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-20 07:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0013_auto_20170120_1451'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playlist',
            options={'ordering': ('-created',)},
        ),
    ]
