# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-21 08:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0014_auto_20170120_1509'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playlistsongsship',
            options={'ordering': ('playlist', 'order')},
        ),
    ]
