# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-18 09:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20170118_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followship',
            name='user_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_from_set', to='accounts.Profile'),
        ),
        migrations.AlterField(
            model_name='followship',
            name='user_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_to_set', to='accounts.Profile'),
        ),
    ]
