# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-18 09:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20170118_1718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followship',
            old_name='user_from',
            new_name='profile_from',
        ),
        migrations.RenameField(
            model_name='followship',
            old_name='user_to',
            new_name='profile_to',
        ),
        migrations.AlterUniqueTogether(
            name='followship',
            unique_together=set([('profile_from', 'profile_to')]),
        ),
    ]
