# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-18 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20170118_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='total_followers',
            field=models.IntegerField(default=0),
        ),
    ]
